---

- name: Create Laravel project
  command: composer create-project --prefer-dist laravel/laravel
  args:
    chdir: /opt/htdocs
    creates: /opt/htdocs/laravel

- name: Copy nginx sites-enabled config
  copy: src=etc/nginx/sites-enabled/laravel.conf dest=/etc/nginx/sites-enabled/laravel.conf

- name: Reload nginx
  include: roles/nginx/handlers/main.yml
  notify: reload nginx

- name: Chown the project
  file: path=/opt/htdocs/laravel state=directory owner=www-data group=www-data recurse=yes