---
- name: Install Mysql packages
  apt: name={{item}} state=present
  with_items:
    - mysql-server
    - mysql-client

- name: Create Mysql configuration file
  template: src=my.cnf dest=/etc/mysql/my.cnf
  notify:
  - restart mysql

