---
- name: Install common services
  apt: name={{item}} state=present
  with_items:
    - vim
    - htop
    - make
    - git
    - git-core
    - libpcre3
    - libpcre3-dev
    - memcached
    - libmysqlclient-dev
    - supervisor

- name: Mount data driver
  service: name=nginx state=stopped

- name: Stop supervisorctl
  command: supervisorctl stop all

- name: Stop mysql
  include: roles/mysql/handlers/main.yml
  notify: stop mysql

- name: Change the limits of authority of apparmor
  copy: src=etc/apparmor.d/local/usr.sbin.mysqld dest=/etc/apparmor.d/local/usr.sbin.mysqld

- name: Prepare the project's directory and move the log's directory
  file: path=/opt/htdocs state=directory owner=www-data group=www-data recurse=yes

- name: Move logs file
  command: cp -Rp /var/log /opt/log

- name: Start supervisorctl
  command: supervisorctl start all

- name: Start mysql
  include: roles/mysql/handlers/main.yml
  notify: start mysql


