---
- name: Install php-fpm and deps
  apt: name={{item}} state=present
  with_items:
    - php5-fpm
    - php5-dev
    - php5-mysqlnd
    - php5-sqlite
    - php5-mongo
    - php5-curl
    - php5-gd
    - php5-intl
    - php5-mcrypt
    - php5-memcached
    - php5-redis
    - php5-gearman
    - php5-xmlrpc
    - php5-memcache
    - php5-msgpack
  notify:
    - enable mod-mcrypt

- name: copy php.ini under cli
  copy: src=etc/php5/cli/php.ini dest=/etc/php5/cli/

- name: copy php.ini under fpm
  copy: src=etc/php5/fpm/php.ini dest=/etc/php5/fpm/

- name: copy pool config
  copy: src=etc/php5/fpm/pool.d/www.conf dest=/etc/php5/fpm/pool.d
  notify: restart php5-fpm

- name: set PHP slow perm
  file: path=/tmp/php-slow.log state=touch mode="u+w,a+r"

