---
- name: start php5-fpm
  service: name=php5-fpm state=started

- name: restart php5-fpm
  service: name=php5-fpm state=restarted

- name: stop php5-fpm
  service: name=php5-fpm state=stopped

- name: reload php5-fpm
  service: name=php5-fpm state=reloaded

- name: enable mod-mcrypt
  command: php5enmod mcrypt